### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by LeeyYun** [pihao/himawari8-desktop#3]
/Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- mini_magick (LoadError)
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/leeyyun/.himawari8_desktop/himawari8_desktop.rb:8:in `req'
	from /Users/leeyyun/.himawari8_desktop/himawari8_desktop.rb:72:in `<main>'

**Comment by LeeyYun** [comment]
imagemagick 和mini_magick 都已安装

**Comment by pihao** [comment]
@LeeyYun 这个感觉是 ruby 的 gem 包环境有问题.

计划周末把这个项目用 Go 重写. 之后不需要安装任何依赖. 直接用 [Homebrew](https://brew.sh/) 安装.

**Comment by LeeyYun** [comment]
@pihao 期待。。。

**Comment by LeeyYun** [comment]
@pihao 安装了之后，没有效果，重启设备之后，电脑登录界面是地球画面，登录之后桌面还是之前的屏保

**Comment by pihao** [comment]
@LeeyYun 你先手动选图片设置一次壁纸, 然后再运行一次`himawari8-desktop`试试.

**Comment by LeeyYun** [comment]
@pihao 还是不行。点击了/usr/local/Cellar/himawari8-desktop/0.0.2/bin/himawari8-desktop 执行文件。会下载图片，成功之后，桌面更换成下载的图片，但是不会随着时间改变。

**Comment by pihao** [comment]
@LeeyYun 是的，现在还没做成服务，有空再搞下

**Comment by pihao** [comment]
@LeeyYun 做成自动更新的服务了. 按 README 里卸载重装试试.
